project:
  type: default

execute:
  echo: false
  warning: false
  message: false
  freeze: auto

format:
  html:
    toc: true
    toc-depth: 3
    number-sections: true
    df-print: paged
  pdf:
    toc: true
    number-sections: true
    header-includes:
      - \usepackage{tgpagella}
      - \usepackage[scaled=0.94]{helvet}
      - \usepackage[scaled=0.9]{inconsolata}

bibliography: references.bib
link-citations: true

crossref:
  tbl-title: Table
  fig-title: Figure
